### ISSUE TITLE
I want to set the Cassandra timezone to UTC + 9 or KST.

### ISSUE THREAD

**Issue by jakim9913** [nosan/embedded-cassandra-spring-boot-starter#130]
I am using Cassandra 3.11.7 with spring boot.
I want to set KST time which is UTC + 9 in Cassandra time zone.
So I'm looking for a way to set the Cassandra timezone.

What should I do?
thank you.

**Comment by nosan** [comment]
You can add `cassandra.embedded.system-properties[user.timezone]=Asia/Seoul` to your `application.properties`

**Comment by nosan** [comment]
Or you can do:
```java

@Bean
	public CassandraBuilderConfigurator timezoneConfigurator(){
		return builder -> builder.addSystemProperty("user.timezone","Asia/Seoul");
	}

```

**Comment by jakim9913** [comment]
Thanks for the reply
However, the code does not work and I get an error.

I don't have CassandraBuilderConfigurator. 
![image](https://user-images.githubusercontent.com/36228033/163898596-38207f90-73d5-496b-ae68-82cf04d2a363.png)

What is CassandraBuilderConfigurator?

I used public class CassandraConfig extends AbstractReactiveCassandraConfiguration  {}

I tried converting the local time as follows, but it doesn't work
```
@Bean
    public CassandraCustomConversions customConversions() {
        List<Converter<?, ?>> converters = new ArrayList<>();
        Set<Converter<?, ?>> converters2 = new HashSet<>();
        converters.add(new MyCustomConverter());

        return new CassandraCustomConversions(converters);
    }
    @ReadingConverter
    public class MyCustomConverter implements Converter<Instant, LocalDateTime> {
        @Override public LocalDateTime convert(Instant instant) { // 여기에서 필요한 변경사항을 적용하면 됩니다.
           // return LocalDateTime.ofInstant(instant, ZoneOffset.of("+09:00"));
            return ZonedDateTime.now(ZoneId.of("Asia/Seoul")).toLocalDateTime();

        }
    }
```

It's a web application, so it shouldn't affect time settings in other parts.

Isn't there a better way?

thank you

**Comment by nosan** [comment]
What version do you use? 

Have tried application properties?

**Comment by jakim9913** [comment]
I am using embedded Cassandra 3.11.7 with spring boot.

```
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-cassandra</artifactId>
            <version>2.2.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.github.nosan</groupId>
            <artifactId>embedded-cassandra-spring-boot-starter</artifactId>
            <version>2.0.5</version>
```


I have application propertise.
```
#Update Property File
#Tue Jan 19 09:46:34 KST 2021
cassandra.password=cassandra
cassandra.username=cassandra
cassandra.keyspace=manage
cassandra.ip=127.0.0.1
cassandra.port=9042
cassandra.jvm.xms=2g
cassandra.jvm.xmx=4g
```

**Comment by nosan** [comment]
Now it is clear :) 


**application.properties:**
```properties
com.github.nosan.embedded.cassandra.system-properties[user.timezone]=Asia/Seoul

```

or

```

@Bean
public CassandraFactoryCustomizer<EmbeddedCassandraFactory> timezoneCustomizer(){
    return cassandraFactory -> cassandraFactory.getSystemProperties().put("user.timezone","Asia/Seoul");
}

```

**Comment by jakim9913** [comment]
thank for the reply.

However, it does not apply.

Here's what's applied:

1. cassandra propertise
  `cassandra.timezone=Asia/Seoul`
2. cassandra config
    `  @Value("${cassandra.timezone}")
    private String timezone;`
3. timezoneCustomizer method add
   `@Bean
    public CassandraFactoryCustomizer<EmbeddedCassandraFactory> timezoneCustomizer(){
        return cassandraFactory -> cassandraFactory.getSystemProperties().put("cassandra.timezone", timezone);
    }
`
4. inser data - create time check   
   
current time : 2022-04-19 17:20:35
DB insert time : 2022-04-19 08:15:35


There is still a 9 hour difference.

**Comment by nosan** [comment]
Why `cassandra.timezone`? Where did you get this?

**Comment by jakim9913** [comment]
I have cassadra.config

```cassandra.password=
cassandra.username=
cassandra.keyspace=manage
cassandra.ip=127.0.0.1
cassandra.port=9042
cassandra.jvm.xms=2g
cassandra.jvm.xmx=4g```

**Comment by nosan** [comment]
```
@Value("${cassandra.timezone}") private String timezone;

    @Bean
    public CassandraFactoryCustomizer<EmbeddedCassandraFactory> timezoneCustomizer() {
        return cassandraFactory -> cassandraFactory.getSystemProperties().put("user.timezone", timezone);
    }

```

**Comment by jakim9913** [comment]
The insert time and the current time are still different.

Is it forced to change to utc timezone when inserted in cassandra?

**Comment by nosan** [comment]
`user.timezone` Java system property explicitly set a default time zone for Apache Cassandra. 
How actually Cassandra treats this property I don't know, it is better to ask Cassandra's team.

**Comment by nosan** [comment]
I believe your question is not related to Embedded Cassandra. Looks like you have a general issue with how to work date-time values in Apache Cassandra.

**Comment by jakim9913** [comment]
thank you for your reply

If you know the Apache Cassandra official contact github address or Q&A site address, please share.

**Comment by nosan** [comment]
https://cassandra.apache.org/_/community.html
